workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

http_jar(
    name = "plantuml",
    sha256 = "eaea0c5777f3ee2c484046d115e2404156bd005961d37dd219f03ae5650375b8",
    url = "https://github.com/plantuml/plantuml/releases/download/v1.2022.7/plantuml-1.2022.7.jar",
)

